"use client"

import * as React from "react"
import { createContext, useContext, useState, useEffect } from "react"

type LanguageContextType = {
  language: string
  setLanguage: (language: string) => void
  t: (key: string, params?: Record<string, any>) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

type Translations = {
  [key: string]: {
    [key: string]: string
  }
}

const translations: Translations = {
  es: {
    "app.mainTitle": "Sistema de Gestión de Biblioteca",
    "app.welcomeMessage": "Gestione sus Materiales, Prestamos, Miembros de manera sencilla.",
    "app.searchPlaceholder": "Buscar",
    "app.viewAll": "Mostrar todo",
    "app.featured": "Destacados",
    "app.viewDetails": "Ver detalles",
    "app.dashboardTitle": "Panel de Control",
    "app.about": "Detalles",
    "app.backToMaterials": "Volver a Materiales",
    "app.confirmPassword": "Confirmar Contraseña",
    "app.haveAccount": "¿Ya tienes una cuenta?",
    "app.registerDescription": "Regístrate para acceder al sistema",
    "app.loginDescription": "Inicia sesión para acceder al sistema",
    "app.noAccount": "¿No tienes una cuenta?",
    "app.invalidCredentials": "Credenciales inválidas",
    "app.manage": "Gestionar",
    "app.material": "Material",
    "app.printAll": "Imprimir todo",
    "app.loanReport": "Reporte de Préstamos",
    "app.printedOn": "Imprimido el",
    "app.createLoan": "Crear Préstamo",
    "app.noUsersFound": "No se encontraron usuarios",
    "app.confirmLoan": "Confirmar Préstamo",
    "app.confirmLoanDescription": "Confirmar Préstamo",
    "app.user": "Usuario",
    "app.backToLoan": "Volver a Préstamos",
    "app.loanCreated": "Préstamo creado correctamente",
    "app.errorCreatingLoan": "Error al crear el préstamo",
    "app.loanUpdated": "Préstamo actualizado correctamente",
    "app.errorUpdatingLoan": "Error al actualizar el préstamo",
    "app.loanDeleted": "Préstamo eliminado correctamente",
    "app.errorDeletingLoan": "Error al eliminar el préstamo",
    "app.confirmApproval": "Confirmar Aprobación",
    "app.backToLoans": "Volver a Préstamos",
    "app.confirmReturn": "Confirmar Devolución",
    "app.dashboard": "Panel de Control",
    "app.materials": "Materiales",
    "app.users": "Usuarios",
    "app.loans": "Préstamos",
    "app.categories": "Categorías",
    "app.collections": "Colecciones",
    "app.materialTypes": "Tipos de Material",
    "app.subjects": "Materias",
    "app.login": "Iniciar Sesión",
    "app.logout": "Cerrar Sesión",
    "app.register": "Registrarse",
    "app.profile": "Perfil",
    "app.settings": "Configuración",
    "app.search": "Buscar",
    "app.add": "Añadir",
    "app.edit": "Editar",
    "app.delete": "Eliminar",
    "app.save": "Guardar",
    "app.cancel": "Cancelar",
    "app.confirm": "Confirmar",
    "app.loading": "Cargando...",
    "app.error": "Error",
    "app.success": "Éxito",
    "app.warning": "Advertencia",
    "app.info": "Información",
    "app.welcome": "Bienvenido",
    "app.welcomeBack": "Bienvenido de nuevo",
    "app.email": "Correo electrónico",
    "app.password": "Contraseña",
    "app.rememberMe": "Recordarme",
    "app.forgotPassword": "¿Olvidaste tu contraseña?",
    "app.dontHaveAccount": "¿No tienes una cuenta?",
    "app.alreadyHaveAccount": "¿Ya tienes una cuenta?",
    "app.createAccount": "Crear cuenta",
    "app.name": "Nombre",
    "app.lastName": "Apellidos",
    "app.phone": "Teléfono",
    "app.identityCard": "Carnet de Identidad",
    "app.address": "Dirección",
    "app.role": "Rol",
    "app.actions": "Acciones",
    "app.librarian": "Bibliotecario",
    "app.member": "Miembro",
    "app.guest": "Invitado",
    "app.title": "Título",
    "app.subtitle": "Subtítulo",
    "app.author": "Autor",
    "app.isbn": "ISBN",
    "app.description": "Descripción",
    "app.quantity": "Cantidad",
    "app.category": "Categoría",
    "app.type": "Tipo",
    "app.status": "Estado",
    "app.available": "Disponible",
    "app.unavailable": "No disponible",
    "app.loanDate": "Fecha de préstamo",
    "app.dueDate": "Fecha de devolución",
    "app.returnDate": "Fecha de retorno",
    "app.borrower": "Prestatario",
    "app.loanedTo": "Prestado a",
    "app.loanedBy": "Prestado por",
    "app.returnedBy": "Devuelto por",
    "app.active": "Activo",
    "app.returned": "Devuelto",
    "app.overdue": "Atrasado",
    "app.requested": "Solicitado",
    "app.rejected": "Rechazado",
    "app.approve": "Aprobar",
    "app.approving": "Aprobando",
    "app.return": "Devolver",
    "app.request": "Solicitar",
    "app.view": "Ver",
    "app.details": "Detalles",
    "app.noUsers": "No hay usuarios",
    "app.noMaterials": "No hay materiales",
    "app.noLoans": "No hay préstamos",
    "app.noCategories": "No hay categorías",
    "app.noCollections": "No hay colecciones",
    "app.noMaterialTypes": "No hay tipos de material",
    "app.noSubjects": "No hay materias",
    "app.addUser": "Añadir Usuario",
    "app.editUser": "Editar Usuario",
    "app.deleteUser": "Eliminar Usuario",
    "app.addUserDescription": "Añadir un nuevo usuario al sistema",
    "app.editUserDescription": "Editar la información del usuario",
    "app.deleteUserConfirmation": "¿Estás seguro de que quieres eliminar este usuario?",
    "app.userAdded": "Usuario añadido correctamente",
    "app.userUpdated": "Usuario actualizado correctamente",
    "app.userDeleted": "Usuario eliminado correctamente",
    "app.errorAddingUser": "Error al añadir el usuario",
    "app.errorUpdatingUser": "Error al actualizar el usuario",
    "app.errorDeletingUser": "Error al eliminar el usuario",
    "app.errorFetchingUsers": "Error al obtener los usuarios",
    "app.selectRole": "Seleccionar rol",
    "app.leaveBlankToKeep": "Dejar en blanco para mantener la contraseña actual",
    "app.manageUsers": "Gestionar Usuarios",
    "app.addMaterial": "Añadir Material",
    "app.editMaterial": "Editar Material",
    "app.deleteMaterial": "Eliminar Material",
    "app.addMaterialDescription": "Añadir un nuevo material al sistema",
    "app.editMaterialDescription": "Editar la información del material",
    "app.deleteMaterialConfirmation": "¿Estás seguro de que quieres eliminar este material?",
    "app.materialAdded": "Material añadido correctamente",
    "app.materialUpdated": "Material actualizado correctamente",
    "app.materialDeleted": "Material eliminado correctamente",
    "app.errorAddingMaterial": "Error al añadir el material",
    "app.errorUpdatingMaterial": "Error al actualizar el material",
    "app.errorDeletingMaterial": "Error al eliminar el material",
    "app.errorFetchingMaterials": "Error al obtener los materiales",
    "app.selectCategory": "Seleccionar categoría",
    "app.manageMaterials": "Gestionar Materiales",
    "app.addLoan": "Añadir Préstamo",
    "app.editLoan": "Editar Préstamo",
    "app.deleteLoan": "Eliminar Préstamo",
    "app.addLoanDescription": "Añadir un nuevo préstamo al sistema",
    "app.editLoanDescription": "Editar la información del préstamo",
    "app.deleteLoanConfirmation": "¿Estás seguro de que quieres eliminar este préstamo?",
    "app.loanAdded": "Préstamo añadido correctamente",
    "app.errorAddingLoan": "Error al añadir el préstamo",
    "app.errorFetchingLoans": "Error al obtener los préstamos",
    "app.selectMaterial": "Seleccionar material",
    "app.selectUser": "Seleccionar usuario",
    "app.manageLoans": "Gestionar Préstamos",
    "app.addCategory": "Añadir Categoría",
    "app.editCategory": "Editar Categoría",
    "app.deleteCategory": "Eliminar Categoría",
    "app.addCategoryDescription": "Añadir una nueva categoría al sistema",
    "app.editCategoryDescription": "Editar la información de la categoría",
    "app.deleteCategoryConfirmation": "¿Estás seguro de que quieres eliminar esta categoría?",
    "app.categoryAdded": "Categoría añadida correctamente",
    "app.categoryUpdated": "Categoría actualizada correctamente",
    "app.categoryDeleted": "Categoría eliminada correctamente",
    "app.errorAddingCategory": "Error al añadir la categoría",
    "app.errorUpdatingCategory": "Error al actualizar la categoría",
    "app.errorDeletingCategory": "Error al eliminar la categoría",
    "app.errorFetchingCategories": "Error al obtener las categorías",
    "app.manageCategories": "Gestionar Categorías",
    "app.addCollection": "Añadir Colección",
    "app.editCollection": "Editar Colección",
    "app.deleteCollection": "Eliminar Colección",
    "app.addCollectionDescription": "Añadir una nueva colección al sistema",
    "app.editCollectionDescription": "Editar la información de la colección",
    "app.deleteCollectionConfirmation": "¿Estás seguro de que quieres eliminar esta colección?",
    "app.collectionAdded": "Colección añadida correctamente",
    "app.collectionUpdated": "Colección actualizada correctamente",
    "app.collectionDeleted": "Colección eliminada correctamente",
    "app.errorAddingCollection": "Error al añadir la colección",
    "app.errorUpdatingCollection": "Error al actualizar la colección",
    "app.errorDeletingCollection": "Error al eliminar la colección",
    "app.errorFetchingCollections": "Error al obtener las colecciones",
    "app.manageCollections": "Gestionar Colecciones",
    "app.addMaterialType": "Añadir Tipo de Material",
    "app.editMaterialType": "Editar Tipo de Material",
    "app.deleteMaterialType": "Eliminar Tipo de Material",
    "app.addMaterialTypeDescription": "Añadir un nuevo tipo de material al sistema",
    "app.editMaterialTypeDescription": "Editar la información del tipo de material",
    "app.deleteMaterialTypeConfirmation": "¿Estás seguro de que quieres eliminar este tipo de material?",
    "app.materialTypeAdded": "Tipo de material añadido correctamente",
    "app.materialTypeUpdated": "Tipo de material actualizado correctamente",
    "app.materialTypeDeleted": "Tipo de material eliminado correctamente",
    "app.errorAddingMaterialType": "Error al añadir el tipo de material",
    "app.errorUpdatingMaterialType": "Error al actualizar el tipo de material",
    "app.errorDeletingMaterialType": "Error al eliminar el tipo de material",
    "app.errorFetchingMaterialTypes": "Error al obtener los tipos de material",
    "app.manageMaterialTypes": "Gestionar Tipos de Material",
    "app.addSubject": "Añadir Materia",
    "app.editSubject": "Editar Materia",
    "app.deleteSubject": "Eliminar Materia",
    "app.addSubjectDescription": "Añadir una nueva materia al sistema",
    "app.editSubjectDescription": "Editar la información de la materia",
    "app.deleteSubjectConfirmation": "¿Estás seguro de que quieres eliminar esta materia?",
    "app.subjectAdded": "Materia añadida correctamente",
    "app.subjectUpdated": "Materia actualizada correctamente",
    "app.subjectDeleted": "Materia eliminada correctamente",
    "app.errorAddingSubject": "Error al añadir la materia",
    "app.errorUpdatingSubject": "Error al actualizar la materia",
    "app.errorDeletingSubject": "Error al eliminar la materia",
    "app.errorFetchingSubjects": "Error al obtener las materias",
    "app.manageSubjects": "Gestionar Materias",
    "app.previous": "Anterior",
    "app.next": "Siguiente",
    "app.of": "de",
    "app.page": "Página",
    "app.searchMaterials": "Buscar materiales",
    "app.searchUsers": "Buscar usuarios",
    "app.searchLoans": "Buscar préstamos",
    "app.searchCategories": "Buscar categorías",
    "app.searchCollections": "Buscar colecciones",
    "app.searchMaterialTypes": "Buscar tipos de material",
    "app.searchSubjects": "Buscar materias",
    "app.basicInfo": "Información Básica",
    "app.detailedInfo": "Información Detallada",
    "app.catalogInfo": "Información de Catálogo",
    "app.copies": "Ejemplares",
    "app.editionInfo": "Información de Edición",
    "app.isOpac": "Es OPAC",
    "app.isOpacDescription": "Mostrar en el catálogo público",
    "app.materialType": "Tipo de Material",
    "app.collection": "Colección",
    "app.language": "Idioma",
    "app.publisher": "Editorial",
    "app.country": "País",
    "app.publicationPlace": "Lugar de Publicación",
    "app.price": "Precio",
    "app.dimensions": "Dimensiones",
    "app.pages": "Páginas",
    "app.registrationNumber": "Número de Registro",
    "app.opac": "OPAC",
    "app.entry1": "Entrada 1",
    "app.entry2": "Entrada 2",
    "app.entry3": "Entrada 3",
    "app.coverImage": "Imagen de Portada",
    "app.preview": "Vista Previa",
    "app.upload": "Subir",
    "app.selectMaterialType": "Seleccionar tipo de material",
    "app.selectCollection": "Seleccionar colección",
    "app.optional": "Opcional",
    "app.manageCopies": "Gestionar Ejemplares",
    "app.addCopy": "Añadir Ejemplar",
    "app.removeCopy": "Eliminar Ejemplar",
    "app.noCopies": "No hay ejemplares",
    "app.addCopyDescription": "Añade ejemplares para poder prestar este material",
    "app.notes": "Notas",
    "app.removeSubject": "Eliminar Materia",
    "app.noSubjectsFound": "No se encontraron materias",
    "app.copyNumber": "Número de ejemplar",
    "app.importMaterials": "Importar Materiales",
    "app.exportMaterials": "Exportar Materiales",
    "app.importMaterialsDescription": "Importar materiales desde un archivo CSV o Excel",
    "app.selectFile": "Seleccionar archivo",
    "app.import": "Importar",
    "app.export": "Exportar",
    "app.importing": "Importando...",
    "app.exporting": "Exportando...",
    "app.importFileFormat": "El archivo debe tener las columnas: título, autor, isbn, categoría, etc.",
    "app.materialsImported": "Se importaron {count} materiales correctamente",
    "app.materialsExported": "Materiales exportados correctamente",
    "app.errorImportingMaterials": "Error al importar los materiales",
    "app.errorExportingMaterials": "Error al exportar los materiales",
    "app.searchOpenLibrary": "Buscar en OpenLibrary",
    "app.searchOpenLibraryDescription": "Busca libros en OpenLibrary para importar sus datos",
    "app.searchByTitleAuthorISBN": "Buscar por título, autor o ISBN",
    "app.searching": "Buscando...",
    "app.noResultsFound": "No se encontraron resultados",
    "app.searchToFindBooks": "Busca para encontrar libros",
    "app.unknownAuthor": "Autor desconocido",
    "app.selectBook": "Seleccionar Libro",
    "app.bookDataImported": "Datos del libro importados correctamente",
    "app.errorSearchingOpenLibrary": "Error al buscar en OpenLibrary",
    "app.errorFetchingBookDetails": "Error al obtener los detalles del libro",
    "app.requestLoan": "Solicitar Préstamo",
    "app.requestLoanDescription": "Solicitar un préstamo de material",
    "app.loanRequested": "Préstamo solicitado correctamente",
    "app.errorRequestingLoan": "Error al solicitar el préstamo",
    "app.loanDetails": "Detalles del Préstamo",
    "app.materialDetails": "Detalles del Material",
    "app.loanId": "ID del Préstamo",
    "app.materialId": "ID del Material",
    "app.userId": "ID del Usuario",
    "app.guestName": "Nombre del Invitado",
    "app.guestEmail": "Correo del Invitado",
    "app.loanNotes": "Notas del Préstamo",
    "app.approveLoan": "Aprobar Préstamo",
    "app.rejectLoan": "Rechazar Préstamo",
    "app.approveLoanDescription": "Aprobar la solicitud de préstamo",
    "app.rejectLoanDescription": "Rechazar la solicitud de préstamo",
    "app.loanApproved": "Préstamo aprobado correctamente",
    "app.loanRejected": "Préstamo rechazado correctamente",
    "app.errorApprovingLoan": "Error al aprobar el préstamo",
    "app.errorRejectingLoan": "Error al rechazar el préstamo",
    "app.returnLoan": "Devolver Préstamo",
    "app.returnLoanDescription": "Registrar la devolución del préstamo",
    "app.loanReturned": "Préstamo devuelto correctamente",
    "app.errorReturningLoan": "Error al devolver el préstamo",
    "app.filters": "Filtros",
    "app.filtersDescription": "Filtrar los resultados",
    "app.allStatuses": "Todos los estados",
    "app.all": "Todos",
    "app.startDate": "Fecha de inicio",
    "app.endDate": "Fecha de fin",
    "app.selectDate": "Seleccionar fecha",
    "app.clearFilters": "Limpiar filtros",
    "app.applyFilters": "Aplicar filtros",
    "app.noLoansDescription": "No hay préstamos que mostrar",
    "app.printLoan": "Imprimir Préstamo",
    "app.printMaterial": "Imprimir Material",
    "app.printPreview": "Vista Previa de Impresión",
    "app.print": "Imprimir",
    "app.printing": "Imprimiendo...",
    "app.exportPDF": "Exportar PDF",
    "app.errorPrinting": "Error al imprimir",
    "app.pdfExportNotImplemented": "La exportación a PDF aún no está implementada",
    "app.signature": "Firma",
    "app.librarianSignature": "Firma del Bibliotecario",
    "app.unknownBorrower": "Prestatario desconocido",
    "app.yes": "Sí",
    "app.no": "No",
    "app.totalMaterials": "Total de Materiales",
    "app.totalUsers": "Total de Usuarios",
    "app.totalLoans": "Total de Préstamos",
    "app.activeLoans": "Préstamos Activos",
    "app.overdueLoans": "Préstamos Atrasados",
    "app.totalCollections": "Total de Colecciones",
    "app.charts": "Gráficos",
    "app.recentActivity": "Actividad Reciente",
    "app.backups": "Copias de Seguridad",
    "app.materialsPerCategory": "Materiales por Categoría",
    "app.popularMaterials": "Materiales Populares",
    "app.recentLoans": "Préstamos Recientes",
    "app.databaseBackups": "Copias de Seguridad de la Base de Datos",
    "app.createBackup": "Crear Copia de Seguridad",
    "app.creatingBackup": "Creando Copia de Seguridad...",
    "app.backupCreated": "Copia de seguridad creada correctamente",
    "app.errorCreatingBackup": "Error al crear la copia de seguridad",
    "app.download": "Descargar",
    "app.restore": "Restaurar",
    "app.restoring": "Restaurando...",
    "app.confirmRestoreBackup": "¿Estás seguro de que quieres restaurar esta copia de seguridad? Se perderán todos los datos actuales.",
    "app.backupRestored": "Copia de seguridad restaurada correctamente",
    "app.errorRestoringBackup": "Error al restaurar la copia de seguridad",
    "app.noBackups": "No hay copias de seguridad",
    "app.noBackupsDescription": "No hay copias de seguridad disponibles",
    "app.errorFetchingBackups": "Error al obtener las copias de seguridad",
    "app.errorDownloadingBackup": "Error al descargar la copia de seguridad",
    "app.loanCount": "Número de préstamos",
    "app.processing": "Procesando...",
    "app.loginError": "Error al iniciar sesión",
    "app.registerError": "Error al registrarse",
    "app.passwordMismatch": "Las contraseñas no coinciden",
    "app.passwordRequirements": "La contraseña debe tener al menos 8 caracteres",
    "app.emailRequired": "El correo electrónico es requerido",
    "app.passwordRequired": "La contraseña es requerida",
    "app.nameRequired": "El nombre es requerido",
    "app.lastNameRequired": "Los apellidos son requeridos",
    "app.phoneRequired": "El teléfono es requerido",
    "app.identityCardRequired": "El carnet de identidad es requerido",
    "app.addressRequired": "La dirección es requerida",
    "app.roleRequired": "El rol es requerido",
    "app.titleRequired": "El título es requerido",
    "app.authorRequired": "El autor es requerido",
    "app.isbnRequired": "El ISBN es requerido",
    "app.descriptionRequired": "La descripción es requerida",
    "app.quantityRequired": "La cantidad es requerida",
    "app.categoryRequired": "La categoría es requerida",
    "app.typeRequired": "El tipo es requerido",
    "app.statusRequired": "El estado es requerido",
    "app.loanDateRequired": "La fecha de préstamo es requerida",
    "app.dueDateRequired": "La fecha de devolución es requerida",
    "app.borrowerRequired": "El prestatario es requerido",
    "app.materialRequired": "El material es requerido",
    "app.userRequired": "El usuario es requerido",
    "app.guestNameRequired": "El nombre del invitado es requerido",
    "app.guestEmailRequired": "El correo del invitado es requerido",
    "app.notesRequired": "Las notas son requeridas",
    "app.languageRequired": "El idioma es requerido",
    "app.publisherRequired": "La editorial es requerida",
    "app.countryRequired": "El país es requerido",
    "app.publicationPlaceRequired": "El lugar de publicación es requerido",
    "app.priceRequired": "El precio es requerido",
    "app.dimensionsRequired": "Las dimensiones son requeridas",
    "app.pagesRequired": "El número de páginas es requerido",
    "app.registrationNumberRequired": "El número de registro es requerido",
    "app.coverImageRequired": "La imagen de portada es requerida",
    "app.copyNumberRequired": "El número de ejemplar es requerido",
    "app.fileRequired": "El archivo es requerido",
    "app.fileFormatError": "Formato de archivo no válido",
    "app.fileSizeError": "El archivo es demasiado grande",
    "app.fileUploadError": "Error al subir el archivo",
    "app.fileDownloadError": "Error al descargar el archivo",
    "app.fileDeleteError": "Error al eliminar el archivo",
    "app.fileNotFound": "Archivo no encontrado",
    "app.fileExists": "El archivo ya existe",
    "app.fileCreated": "Archivo creado correctamente",
    "app.fileUpdated": "Archivo actualizado correctamente",
    "app.fileDeleted": "Archivo eliminado correctamente",
    "app.fileImported": "Archivo importado correctamente",
    "app.fileExported": "Archivo exportado correctamente",
    "app.fileProcessing": "Procesando archivo...",
    "app.fileProcessingError": "Error al procesar el archivo",
    "app.fileProcessingSuccess": "Archivo procesado correctamente",
    "app.fileProcessingCancelled": "Procesamiento de archivo cancelado",
    "app.fileProcessingTimeout": "Tiempo de espera agotado al procesar el archivo",
    "app.fileProcessingInvalid": "Archivo inválido",
    "app.fileProcessingEmpty": "El archivo está vacío",
    "app.fileProcessingTooLarge": "El archivo es demasiado grande",
    "app.fileProcessingTooSmall": "El archivo es demasiado pequeño",
    "app.fileProcessingUnsupported": "Formato de archivo no soportado",
    "app.fileProcessingCorrupted": "El archivo está corrupto",
    "app.fileProcessingIncomplete": "El archivo está incompleto",
    "app.fileProcessingFailed": "Error al procesar el archivo",
    "app.reject": "Rechazar",
    "app.loadingDashboard": "Cargando dashboard...",
    "app.materialsInLibrary": "Materiales en la biblioteca",
    "app.registeredUsers": "Usuarios registrados",
    "app.totalLoansProcessed": "Préstamos procesados",
    "app.currentlyActive": "Préstamos activos",
    "app.needAttention": "Préstamos atrasados",
    "app.availableCollections": "Colecciones disponibles",
    "app.visualizeLibraryData": "Ver datos de la biblioteca",
    "app.noDataAvailable": "No hay datos disponibles",
    "app.createBackupDescription": "Crear una copia de seguridad de la base de datos",
    "app.registrationSuccess":"Registro exitoso",
    "app.registrationFailed":"Error al registrar",
    "app.confirmLoanRequest":"Confirmar Préstamo",
    "app.confirmLoanRequestDescription":"Confirmar Préstamo",
    "app.confirmRequest":"Confirmar",
    "app.loanRequestSuccess":"Préstamo confirmado exitosamente",
    "app.loanRequestFailed":"Error al confirmar préstamo",
    "app.userProfile":"Perfil de usuario",
    "app.loanHistory":"Historial de préstamos",
    "app.updateProfile":"Actualizar perfil",
    "app.changePassword":"Cambiar contraseña",
    "app.currentPassword":"Contraseña actual",
    "app.newPassword":"Nueva contraseña",
    "app.selectType":"Seleccionar tipo de material",
    "app.addCopiesDescription":"Añadir copias de este material",
    "app.copyNotesPlaceholder":"Añadir notas para esta copia"

    
  },
  en: {
    "app.mainTitle": "Library Management System",
    "app.welcomeMessage": "Manage your Materials, Loans, Members easily.",
    "app.searchPlaceholder": "Search",
    "app.viewAll": "View all",
    "app.featured": "Featured",
    "app.viewDetails": "View details",
    "app.dashboardTitle": "Dashboard",
    "app.about": "About",
    "app.backToMaterials": "Back to Materials",
    "app.confirmPassword": "Confirm Password",
    "app.haveAccount": "Do you have an account?",
    "app.registerDescription": "Register to access the system",
    "app.loginDescription": "Login to access the system",
    "app.noAccount": "Don't have an account?",
    "app.invalidCredentials": "Invalid credentials",
    "app.manage": "Manage",
    "app.material": "Material",
    "app.printAll": "Print All",
    "app.loanReport": "Loan Report",
    "app.printedOn": "Printed On",
    "app.createLoan": "Create Loan",
    "app.noUsersFound": "No users found",
    "app.confirmLoan": "Confirm Loan",
    "app.confirmLoanDescription": "Confirm Loan",
    "app.user": "User",
    "app.backToLoan": "Back to Loans",
    "app.loanCreated": "Loan created successfully",
    "app.errorCreatingLoan": "Error creating loan",
    "app.loanUpdated": "Loan updated successfully",
    "app.errorUpdatingLoan": "Error updating loan",
    "app.loanDeleted": "Loan deleted successfully",
    "app.errorDeletingLoan": "Error deleting loan",
    "app.confirmApproval": "Confirm Approval",
    "app.backToLoans": "Back to Loans",
    "app.confirmReturn": "Confirm Return",
    "app.dashboard": "Dashboard",
    "app.materials": "Materials",
    "app.users": "Users",
    "app.loans": "Loans",
    "app.categories": "Categories",
    "app.collections": "Collections",
    "app.materialTypes": "Material Types",
    "app.subjects": "Subjects",
    "app.login": "Login",
    "app.logout": "Logout",
    "app.register": "Register",
    "app.profile": "Profile",
    "app.settings": "Settings",
    "app.search": "Search",
    "app.add": "Add",
    "app.edit": "Edit",
    "app.delete": "Delete",
    "app.save": "Save",
    "app.cancel": "Cancel",
    "app.confirm": "Confirm",
    "app.loading": "Loading...",
    "app.error": "Error",
    "app.success": "Success",
    "app.warning": "Warning",
    "app.info": "Information",
    "app.welcome": "Welcome",
    "app.welcomeBack": "Welcome back",
    "app.email": "Email",
    "app.password": "Password",
    "app.rememberMe": "Remember me",
    "app.forgotPassword": "Forgot your password?",
    "app.dontHaveAccount": "Don't have an account?",
    "app.alreadyHaveAccount": "Already have an account?",
    "app.createAccount": "Create account",
    "app.name": "Name",
    "app.lastName": "Last Name",
    "app.phone": "Phone",
    "app.identityCard": "Identity Card",
    "app.address": "Address",
    "app.role": "Role",
    "app.actions": "Actions",
    "app.librarian": "Librarian",
    "app.member": "Member",
    "app.guest": "Guest",
    "app.title": "Title",
    "app.subtitle": "Subtitle",
    "app.author": "Author",
    "app.isbn": "ISBN",
    "app.description": "Description",
    "app.quantity": "Quantity",
    "app.category": "Category",
    "app.type": "Type",
    "app.status": "Status",
    "app.available": "Available",
    "app.unavailable": "Unavailable",
    "app.loanDate": "Loan Date",
    "app.dueDate": "Due Date",
    "app.returnDate": "Return Date",
    "app.borrower": "Borrower",
    "app.loanedTo": "Loaned to",
    "app.loanedBy": "Loaned by",
    "app.returnedBy": "Returned by",
    "app.active": "Active",
    "app.returned": "Returned",
    "app.overdue": "Overdue",
    "app.requested": "Requested",
    "app.rejected": "Rejected",
    "app.approve": "Approve",
    "app.approving": "Approving",
    "app.return": "Return",
    "app.request": "Request",
    "app.view": "View",
    "app.details": "Details",
    "app.noUsers": "No users",
    "app.noMaterials": "No materials",
    "app.noLoans": "No loans",
    "app.noCategories": "No categories",
    "app.noCollections": "No collections",
    "app.noMaterialTypes": "No material types",
    "app.noSubjects": "No subjects",
    "app.addUser": "Add User",
    "app.editUser": "Edit User",
    "app.deleteUser": "Delete User",
    "app.addUserDescription": "Add a new user to the system",
    "app.editUserDescription": "Edit user information",
    "app.deleteUserConfirmation": "Are you sure you want to delete this user?",
    "app.userAdded": "User added successfully",
    "app.userUpdated": "User updated successfully",
    "app.userDeleted": "User deleted successfully",
    "app.errorAddingUser": "Error adding user",
    "app.errorUpdatingUser": "Error updating user",
    "app.errorDeletingUser": "Error deleting user",
    "app.errorFetchingUsers": "Error fetching users",
    "app.selectRole": "Select role",
    "app.leaveBlankToKeep": "Leave blank to keep current password",
    "app.manageUsers": "Manage Users",
    "app.addMaterial": "Add Material",
    "app.editMaterial": "Edit Material",
    "app.deleteMaterial": "Delete Material",
    "app.addMaterialDescription": "Add a new material to the system",
    "app.editMaterialDescription": "Edit material information",
    "app.deleteMaterialConfirmation": "Are you sure you want to delete this material?",
    "app.materialAdded": "Material added successfully",
    "app.materialUpdated": "Material updated successfully",
    "app.materialDeleted": "Material deleted successfully",
    "app.errorAddingMaterial": "Error adding material",
    "app.errorUpdatingMaterial": "Error updating material",
    "app.errorDeletingMaterial": "Error deleting material",
    "app.errorFetchingMaterials": "Error fetching materials",
    "app.selectCategory": "Select category",
    "app.manageMaterials": "Manage Materials",
    "app.addLoan": "Add Loan",
    "app.editLoan": "Edit Loan",
    "app.deleteLoan": "Delete Loan",
    "app.addLoanDescription": "Add a new loan to the system",
    "app.editLoanDescription": "Edit loan information",
    "app.deleteLoanConfirmation": "Are you sure you want to delete this loan?",
    "app.loanAdded": "Loan added successfully",
    "app.errorAddingLoan": "Error adding loan",
    "app.errorFetchingLoans": "Error fetching loans",
    "app.selectMaterial": "Select material",
    "app.selectUser": "Select user",
    "app.manageLoans": "Manage Loans",
    "app.basicInfo": "Basic Information",
    "app.detailedInfo": "Detailed Information",
    "app.catalogInfo": "Catalog Information",
    "app.copies": "Copies",
    "app.editionInfo": "Edition Information",
    "app.isOpac": "Is OPAC",
    "app.isOpacDescription": "Show in public catalog",
    "app.materialType": "Material Type",
    "app.collection": "Collection",
    "app.language": "Language",
    "app.publisher": "Publisher",
    "app.country": "Country",
    "app.publicationPlace": "Publication Place",
    "app.price": "Price",
    "app.dimensions": "Dimensions",
    "app.pages": "Pages",
    "app.registrationNumber": "Registration Number",
    "app.opac": "OPAC",
    "app.coverImage": "Cover Image",
    "app.preview": "Preview",
    "app.upload": "Upload",
    "app.selectMaterialType": "Select material type",
    "app.selectCollection": "Select collection",
    "app.optional": "Optional",
    "app.manageCopies": "Manage Copies",
    "app.addCopy": "Add Copy",
    "app.removeCopy": "Remove Copy",
    "app.noCopies": "No copies",
    "app.addCopyDescription": "Add copies to be able to loan this material",
    "app.notes": "Notes",
    "app.manageSubjects": "Manage Subjects",
    "app.removeSubject": "Remove Subject",
    "app.noSubjectsFound": "No subjects found",
    "app.addSubjectDescription": "Add subjects to categorize this material",
    "app.searchSubjects": "Search subjects",
    "app.printLoan": "Print Loan",
    "app.printMaterial": "Print Material",
    "app.printPreview": "Print Preview",
    "app.print": "Print",
    "app.printing": "Printing...",
    "app.exportPDF": "Export PDF",
    "app.errorPrinting": "Error printing",
    "app.pdfExportNotImplemented": "PDF export not yet implemented",
    "app.processing": "Processing...",
    "app.loginError": "Login error",
    "app.registerError": "Registration error",
    "app.passwordMismatch": "Passwords do not match",
    "app.passwordRequirements": "Password must be at least 8 characters long",
    "app.emailRequired": "Email is required",
    "app.passwordRequired": "Password is required",
    "app.nameRequired": "Name is required",
    "app.lastNameRequired": "Last name is required",
    "app.phoneRequired": "Phone is required",
    "app.identityCardRequired": "Identity card is required",
    "app.addressRequired": "Address is required",
    "app.roleRequired": "Role is required",
    "app.titleRequired": "Title is required",
    "app.authorRequired": "Author is required",
    "app.isbnRequired": "ISBN is required",
    "app.descriptionRequired": "Description is required",
    "app.quantityRequired": "Quantity is required",
    "app.categoryRequired": "Category is required",
    "app.typeRequired": "Type is required",
    "app.statusRequired": "Status is required",
    "app.loanDateRequired": "Loan date is required",
    "app.dueDateRequired": "Due date is required",
    "app.borrowerRequired": "Borrower is required",
    "app.materialRequired": "Material is required",
    "app.userRequired": "User is required",
    "app.guestNameRequired": "Guest name is required",
    "app.guestEmailRequired": "Guest email is required",
    "app.notesRequired": "Notes are required",
    "app.languageRequired": "Language is required",
    "app.publisherRequired": "Publisher is required",
    "app.countryRequired": "Country is required",
    "app.publicationPlaceRequired": "Publication place is required",
    "app.priceRequired": "Price is required",
    "app.dimensionsRequired": "Dimensions are required",
    "app.pagesRequired": "Number of pages is required",
    "app.registrationNumberRequired": "Registration number is required",
    "app.coverImageRequired": "Cover image is required",
    "app.copyNumberRequired": "Copy number is required",
    "app.fileRequired": "File is required",
    "app.fileFormatError": "Invalid file format",
    "app.fileSizeError": "File is too large",
    "app.fileUploadError": "Error uploading file",
    "app.fileDownloadError": "Error downloading file",
    "app.fileDeleteError": "Error deleting file",
    "app.fileNotFound": "File not found",
    "app.fileExists": "File already exists",
    "app.fileCreated": "File created successfully",
    "app.fileUpdated": "File updated successfully",
    "app.fileDeleted": "File deleted successfully",
    "app.fileImported": "File imported successfully",
    "app.fileExported": "File exported successfully",
    "app.fileProcessing": "Processing file...",
    "app.fileProcessingError": "Error processing file",
    "app.fileProcessingSuccess": "File processed successfully",
    "app.fileProcessingCancelled": "File processing cancelled",
    "app.fileProcessingTimeout": "File processing timeout",
    "app.fileProcessingInvalid": "Invalid file",
    "app.fileProcessingEmpty": "File is empty",
    "app.fileProcessingTooLarge": "File is too large",
    "app.fileProcessingTooSmall": "File is too small",
    "app.fileProcessingUnsupported": "Unsupported file format",
    "app.fileProcessingCorrupted": "File is corrupted",
    "app.fileProcessingIncomplete": "File is incomplete",
    "app.fileProcessingFailed": "File processing failed",
    "app.reject": "Reject",
    "app.materialsInLibrary": "Materials in library",
    "app.registeredUsers": "Registered users",
    "app.totalLoansProcessed": "Total loans processed",
    "app.currentlyActive": "Currently active",
    "app.needAttention": "Need attention",
    "app.availableCollections": "Available collections",
    "app.visualizeLibraryData": "Visualize library data",
    "app.noDataAvailable": "No data available",
    "app.createBackupDescription": "Create a backup of the database",
    
    "app.registrationFailed":"Registration Failed",
    "app.registrationSuccess":"Registration Success",
    "app.confirmLoanRequest":"Confirm Loan Request",
    "app.confirmLoanRequestDescription":"Confirm Loan Request",
    "app.confirmRequest":"Confirm Request",
    "app.loanRequestSuccess":"Loan request confirmed successfully",
    "app.loanRequestFailed":"Error confirming loan request",
    "app.userProfile":"User Profile",
    "app.loanHistory":"Loan History",
    "app.updateProfile":"Update Profile",
    "app.changePassword":"Change Password",
    "app.currentPassword":"Current password",
    "app.newPassword":"New password",
    "app.selectType":"Select material type",
    "app.addCopiesDescription":"Add copies of this material",
    "app.copyNotesPlaceholder":"Add notes for this copy"



    
  },
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState("es")

  useEffect(() => {
    const savedLanguage = localStorage.getItem("language")
    if (savedLanguage) {
      setLanguage(savedLanguage)
    }
  }, [])

  const t = (key: string, params?: Record<string, any>) => {
    const translation = translations[language][key] || key
    if (params) {
      return Object.entries(params).reduce((acc, [key, value]) => {
        return acc.replace(`{${key}}`, value)
      }, translation)
    }
    return translation
  }

  const changeLanguage = (newLanguage: string) => {
    setLanguage(newLanguage)
    localStorage.setItem("language", newLanguage)
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
} 